### ISSUE TITLE
핵심기능구현#5

### ISSUE THREAD

**Issue by colorful-ahn** [JungJaeLee-JJ/kkuuk_front#7]
1. xd내 모든 핵심 기능 구현
2. 배포

**Comment by JungJaeLee-JJ** [comment]
로딩 스피너 및 사용자 알림(모달)

배포는 아래 순서대로 좋을듯
1. 엠플리 파이로 ci/cd 구축
2. aws eb 로 배포하고, codepipeline 연결하여 ci/cd 구축
-- 간지 안나는 방법 --
3. ec2 안에서 pm2로 백그라운드 실행
4. nginx로 빌드된 react 파일 연결
